config/routes.rb
Rails.application.routes.draw do
  resources :articles 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    after_create_commit { broadcast_prepend_to "articles-list" }
    after_update_commit { broadcast_replace_to "articles-list" }
    after_destroy_commit { broadcast_remove_to "articles-list" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    if params[:title].present?
      @articles = Article.all.select { |a| a.title.downcase.include? params[:title].downcase }
    else
      @articles = Article.all.order(created_at: :desc)
    end
    
    if turbo_frame_request?
      render partial: "articles", locals: {articles: @articles}
    else
      render :index
    end
  end
  
  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('new_article', partial: 'articles/form', locals: {article: Article.new}),
            turbo_stream.prepend('articles', partial: 'articles/article', locals: {article: @article}),
          ]
        end
        format.html { redirect_to root_path, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('new_article', partial: 'articles/form', locals: {article: @article})
          ]
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.turbo_stream 
      # { render turbo_stream: turbo_stream.remove(@article) }  
      format.html { redirect_to root_path, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%=dom_id article%>" class="shadow-xl my-8 p-4 rounded-lg bg-white">
  <%=turbo_frame_tag dom_id(article, 'edit') do%>
    <div>
        <div class="flex flex-row justify-end gap-4">
        <%= link_to  edit_article_path(article), class: "flex justify-end w-full mr-auto" do%>
        <i class="fa-solid fa-pen-fancy text-indigo-400 hover:text-indigo-500 ease-out duration-300 transition cursor-pointer"></i>
        <%end%>
        <%= button_to  article_path(article), method: :delete, class: "flex justify-end w-full mr-auto" do%>
          <i class="fa-solid fa-xmark text-red-400 hover:text-red-500 ease-out duration-300 transition cursor-pointer"></i>
        <%end%>
      </div>
    </div>
    <p class="my-4">
      <strong class="block font-medium mb-1">Title:</strong>
      <%= article.title %>
    </p>
    
    <p class="my-4 break-words">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= article.description %>
    </p>
    <%#= link_to "Show this article", article, class: "rounded-lg py-3 px-5 bg-indigo-300 inline-block font-medium hover:bg-indigo-400 ease-out duration-300 transition" %>


  <%end%>

</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles-search" do%>
  <div id="articles">
    <%= render @articles %>
  </div>
<%end%>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div data-alert-text-value="hello" data-controller="alert" id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <button data-alert-target="btn" class="w-full text-right" data-action="click->alert#close">x</button>
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, autocomplete:"off",class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 2, autocomplete:"off",class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-indigo-500 inline-block font-medium hover:bg-indigo-600 ease-out duration-300 transition cursor-pointer text-white" %>
  </div>
<% end %>

app/views/articles/_search_form.html.erb
<%# , turbo_action: "advance" %>
<div class="flex justify-end mb-1">
  <%= form_with url: articles_path, method: :get, data: {controller: "search", turbo_frame: "articles-search"}, class: "flex gap-4 flex-row justify-end items-center" do |form| %>
    <%= form.text_field :title, 
                        placeholder: "Search by title", 
                        value: params[:title], 
                        class: "w-full border border-blue-500 rounded p-2 h-fit ", 
                        autocomplete: "off", 
                        data: {action: "input->search#searchForm"} %>
  <% end %>
</div>

app/views/articles/destroy.turbo_stream.erb
<%=turbo_stream.remove @article%>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing article</h1>
  
  <%=turbo_frame_tag dom_id(@article, 'edit') do%>
    <%= render "form", article: @article %>
    <%= link_to "Back to articles", root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%end%>

  <%= link_to "Show this article", @article, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <h1 class="font-bold text-2xl">Create new article</h1>
  <div id="new_article" class="rounded-lg mb-20 shadow-xl my-8 p-8 bg-white">
    <%=render partial: 'articles/form', locals: {article: Article.new}%>
  </div>
  <div class="mb-8 font-bold text-lg"><%=Time.zone.now%></div>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">Articles</h1>
    <%=render 'search_form'%>
    <%#= link_to 'New article', new_article_path, class: "rounded-lg py-3 px-5 bg-indigo-300 hover:bg-indigo-400 transition ease-out duration-300 text-white block font-medium" %>
  </div>

  <div class="min-w-full mb-40">
    <%= turbo_stream_from "articles-list" %>
      <%= render 'articles'%>
  </div>
</div>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New article</h1>

  <%= render "form", article: @article %>

  <%= link_to 'Back to articles', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @article %>
     
    <%= link_to 'Edit this article', edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this article', article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to articles', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
   
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>